### ISSUE TITLE
Rename this software

### ISSUE THREAD

**Issue by bleve** [krestomatio/pppxy#1]
There is already very well known ppp software which is point to point protocol implementation.

https://datatracker.ietf.org/doc/html/rfc1661

https://ppp.samba.org/

All distributions have package called ppp.

**Comment by jobcespedes** [comment]
You are right. Any suggestions for the name?

**Comment by bleve** [comment]
proxy-protocol-proxy

I don't see any reason to shorten.

**Comment by jobcespedes** [comment]
Package names in Go and other places like docs, usually require a shortened version of the name. What about pppxy o ppproxy for that case?

**Comment by jobcespedes** [comment]
I decided on pppxy. Thanks
